version: '3'

services:
  backend:
    build:
      context: ./backend
    container_name: flask-container
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    container_name: react-container
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:4.4
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
