name: Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -r backend/requirements.txt --upgrade pip
      working-directory: ./backend

    - name: Run tests
      run: |
        . venv/bin/activate
        pytest
      working-directory: ./backend

  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -r backend/requirements.txt --upgrade pip
      working-directory: ./backend

    - name: Build Docker image
      run: docker build -t backend:latest ./backend

    - name: Push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker tag backend:latest $DOCKER_USERNAME/backend:latest
        docker push $DOCKER_USERNAME/backend:latest
